package Exceptions;

public class Lab162 {

	public static void main(String[] args)
	{

		
	    try {
		int a =10;
	    int b=0;
	    int c=a/b;
		System.out.println(c);
		}catch(Exception e)
		
		{
		System.out.println("Handling the exception");
		}
		//Handling the exception using the try-catch block
		
		
	}
}
